import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Google Search Results Scraper API | ScrapingBee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.jpg" type="image/jpeg" />
      </head>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
